version: '3'
networks:
   db-net:
     external:
         name: wellcheckv2_db-net
   proxy:
     external:
         name: wellcheckv2_proxy

services:
   kibana:
     image: docker.elastic.co/kibana/kibana:7.6.0
     volumes:
       - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
     networks:
       - db-net
       - proxy

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:
       - PMA_ARBITRARY=1
     restart: always
     volumes:
       - /sessions
     external_links:
       - datab:db
     networks:
       - db-net
       - proxy
     environment:
       PMA_USER: ${DB_USER}
       PMA_PASSWORD: ${DB_PASS}

   goaccess:
     image: nginx
     container_name: goaccess
     restart: always
     volumes:
       - ./goaccess/html:/usr/share/nginx/html:ro
     networks:
       - proxy

   goaccesscli:
    image: allinurl/goaccess
    container_name: goaccesscli
    volumes:
      - ./custom:/logs/
      - ./goaccess/conf:/etc/goaccess/
      - ./goaccess/html:/results/
    entrypoint: "watch `goaccess /logs/${DOMAIN}.log -o /results/${DOMAIN}.html --log-format=COMBINED;
                        goaccess /logs/dashboard.${DOMAIN}.log -o /results/dashboard${DOMAIN}.html --log-format=COMBINED;
                        goaccess /logs/api.${DOMAIN}.log -o /results/api${DOMAIN}.html --log-format=COMBINED;`
                "

   admin:
    image: nginx
    container_name: admin
    restart: always
    volumes:
     - ./admin/html:/usr/share/nginx/html:ro
     - ./admin/conf/admin.conf:/etc/nginx/conf.d/default.conf:ro
    links:
     - goaccess
     - phpmyadmin
     - kibana
    networks:
     - proxy
    environment:
     VIRTUAL_HOST: admin.${DOMAIN}
     VIRTUAL_PORT: 80
     LETSENCRYPT_HOST: admin.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}
