version: '3'

networks:
  proxy:
    external:
        name: docker-compose_proxy

services:
  wellcheck_landing:
    image: nginx
    container_name: wellcheck_landing
    restart: always
    volumes:
      - ../Wellcheck/Webapps/wellcheck/front:/usr/share/nginx/html:ro
      - ../Wellcheck/Webapps/wellcheck/conf/landing.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - wellcheck_error
      - wellcheck_php
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: ${DOMAIN}, www.${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN}, www.${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}

  wellcheck_documents:
    image: nginx
    container_name: wellcheck_documents
    restart: always
    volumes:
      - ../Wellcheck/Webapps/doc.wellcheck/front:/usr/share/nginx/html:ro
      - ../Wellcheck/Webapps/doc.wellcheck/conf/doc.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - wellcheck_error
      - wellcheck_php
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: doc.${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: doc.${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}

  wellcheck_php:
    image: php:fpm-alpine
    container_name: wellcheck_php
    restart: always
    volumes:
      - ../Wellcheck/Webapps/wellcheck/front:/script:ro
      - ../Wellcheck/Webapps/doc.wellcheck/front:/doc:ro
      - ../Wellcheck/Webapps/doc.wellcheck/save:/savedoc
      - ../Wellcheck/Admin/services/contact:/result
    networks:
      - proxy

  wellcheck_error:
    image: nginx
    container_name: wellcheck_error
    restart: always
    volumes:
      - ../Wellcheck/Webapps/error.wellcheck/front:/usr/share/nginx/html:ro
      - ../Wellcheck/Webapps/error.wellcheck/conf/error.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
